#!/usr/bin/env bash
# postclass_generate.sh - auto-generate post-class feedback after transcription
# Usage: postclass_generate.sh <session_dir> <vault_path>
# Exit 0: success, 1: error, 2: no calendar match (skip feedback)
set -uo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

SESSION_DIR="$1"
VAULT_PATH="$2"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TRANSCRIPT="$SESSION_DIR/transcript.txt"
[ -f "$TRANSCRIPT" ] || { echo "no transcript: $TRANSCRIPT"; exit 1; }

# Match student from calendar
MATCH=$("$SCRIPT_DIR/match_calendar_event.sh" 2>/dev/null) || { echo "no calendar match, skipping feedback"; exit 2; }
SYSTEM="${MATCH%%|*}"
STUDENT="${MATCH##*|}"
[ -z "$STUDENT" ] && { echo "empty student name"; exit 2; }

CONTENT=$(head -c 8000 "$TRANSCRIPT")
DATE=$(date '+%Y-%m-%d')

# Detect proxy
PROXY=""
for var in https_proxy HTTPS_PROXY http_proxy HTTP_PROXY all_proxy; do
  [ -n "${!var:-}" ] && { PROXY="${!var}"; break; }
done
if [ -z "$PROXY" ]; then
  PROXY=$(scutil --proxy 2>/dev/null | awk '
    /HTTPSEnable|HTTPEnable/{e=$3}
    /HTTPSProxy|HTTPProxy/{if(!h)h=$3}
    /HTTPSPort|HTTPPort/{if(!p)p=$3}
    END{if(e==1 && h && p) print "http://"h":"p}')
fi

# Read API key
GROQ_API_KEY="${GROQ_API_KEY:-}"
if [ -z "$GROQ_API_KEY" ] && [ -f "$HOME/.zshrc" ]; then
  GROQ_API_KEY=$(grep -E '^[[:space:]]*(export[[:space:]]+)?GROQ_API_KEY=' "$HOME/.zshrc" | tail -1 | sed -E 's/^[^=]*=[[:space:]]*//; s/^["'"'"']+//; s/["'"'"']+$//')
fi
[ -z "$GROQ_API_KEY" ] && { echo "GROQ_API_KEY not found"; exit 1; }

# Build prompt - strict evidence-based, low hallucination
PROMPT="You are an experienced physics teacher writing a post-class feedback report in Chinese.

CRITICAL RULES:
- ONLY include information that is EXPLICITLY stated or clearly demonstrated in the transcript below.
- Do NOT invent, assume, or fabricate any events, questions, behaviors, or topics that are not in the transcript.
- If the transcript is too short or unclear to determine something, write '无法从录音判断' instead of guessing.
- The transcript is auto-generated by speech recognition and may contain errors or fragmented sentences. Interpret charitably but do not add content.

Student: $STUDENT
Course system: $SYSTEM
Date: $DATE

Based on the transcript, generate feedback with these sections:
1. # 课后反馈 - $STUDENT - $DATE
2. ## 本节课主题 (one sentence, only if clearly identifiable)
3. ## 表现亮点 (1-2 points, ONLY if there is clear evidence in the transcript)
4. ## 待改进 (1-2 points, ONLY if there is clear evidence)
5. ## 建议 (1-2 homework suggestions based on the topic covered)

Total length: 300-500 Chinese characters.

Transcript:
$CONTENT"

# Build JSON payload via python3
PAYLOAD=$(echo "$PROMPT" | python3 -c "
import json, sys
prompt = sys.stdin.read()
print(json.dumps({'model':'llama-3.1-8b-instant','messages':[{'role':'user','content':prompt}],'temperature':0.3,'max_tokens':1024}))
")

# Call Groq
CURL_ARGS=(-s --max-time 120 https://api.groq.com/openai/v1/chat/completions
  -H "Authorization: Bearer $GROQ_API_KEY"
  -H "Content-Type: application/json"
  -d "$PAYLOAD")
[ -n "$PROXY" ] && CURL_ARGS+=(-x "$PROXY")

RESPONSE=$(curl "${CURL_ARGS[@]}")
FEEDBACK=$(echo "$RESPONSE" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d["choices"][0]["message"]["content"])' 2>/dev/null)
[ -z "$FEEDBACK" ] && { echo "Groq parse failed: ${RESPONSE:0:200}"; exit 1; }

# Write to Vault
FEEDBACK_DIR="$VAULT_PATH/上课记录/课后反馈"
mkdir -p "$FEEDBACK_DIR"
OUTFILE="$FEEDBACK_DIR/${DATE}-${STUDENT}-feedback.md"
echo "$FEEDBACK" > "$OUTFILE"
echo "$OUTFILE"
